services:
  gha-runner-amd64:
    build:
      context: .
      args:
        TARGETARCH: amd64
    platform: linux/amd64
    restart: always
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2376
    env_file:
      - container-vars.env
    volumes:
      - docker-certs-client:/certs/client:ro
      - type: bind
        source: private.pem
        target: /tmp/private.pem
    depends_on:
      docker:
        condition: service_healthy
    networks:
      - runner-network
    deploy:
      resources:
        limits:
          cpus: 8
  docker:
    image: docker:dind
    privileged: true
    restart: always
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-var-lib-docker:/var/lib/docker
    healthcheck:
      test: ["CMD-SHELL", "docker version > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - runner-network

  bazel-cache:
    container_name: bazel-remote-cache
    image: buchgr/bazel-remote-cache:v1.3.4
    restart: always
    networks:
      - runner-network
    # make ports 9090 (mapped to 8080) and 9092 available other services but NOT to the host
    expose:
      - 9090:8080
      - 9092:9092
    # note: --max_size is in GB
    command: --max_size=25
    # NOTE: mount a docker volume directory as /data to persist the cache
    volumes:
      - bazel-cache:/data
    environment:
      BAZEL_REMOTE_GRPC_PORT: 9092


volumes:
  docker-certs-client:
  docker-certs-ca:
  docker-var-lib-docker:
  bazel-cache:

networks:
  runner-network:
    driver: bridge
